service: serverless-lambda

frameworkVersion: "1"

plugins:
  - serverless-offline
  - serverless-offline-scheduler
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:AWS_STAGE}
  region: ${env:AWS_REGION}

functions:
  hello:
    handler: handler.hello
  message:
    handler: handler.message
    events:
      - http:
          path: message/{name}
          method: get
  cronjob:
    handler: handler.cronjob
    events:
      - schedule: rate(1 minutes)
